### ISSUE TITLE
Link to the help under Resources needs to be updated

### ISSUE THREAD

**Issue by jen-jackson** [Esri/landscape-modeler-js#31]
The Landscape Modeler Help link needs to be updated to use the following URL: http://resources.arcgis.com/en/help/landscape-modeler/guide/

The current URL (http://resources.arcgis.com/en/help/landscape-modeler/index.html#/) does not have the information on how to prepare your own data for use with Landscape Modeler.

**Comment by tomwayson** [comment]
Also need to emphasize that `dummyRasterId` _almost always_ needs to be changed from the default value in src/app/config.js.

Should consider moving [configuring app section of README](https://github.com/Esri/landscape-modeler-js#configuring-the-application) to wiki, since it requires frequent updating.

**Comment by tomwayson** [comment]
I've created [the wiki](https://github.com/Esri/landscape-modeler-js/wiki). Will address w/ this issue by removing all redundant content from README and adding a link to wiki.
